### ISSUE TITLE
Exception Predicate Missing from Master

### ISSUE THREAD

**Issue by coreagile** [liwp/again#8]
Congratulations on 1.0.0! I noticed that the pull request we submitted allowing you to configure an exception predicate didn't make it in. Would you like me to submit a new one based off master, including README updates?

**Comment by coreagile** [comment]
Ahh.. I see what happened. You improved it by integrating it with the callback approach. I'll take a look and see how we can update our code to take advantage of the new approach!

**Comment by liwp** [comment]
Do let me know if it doesn't work for your use case and we'll try to fix it. I just wasn't comfortable adding another callback function to the options map since I felt that the predicate should also be provided with retry counts, user context etc, ie all the things that the existing callback is provided with.

**Comment by coreagile** [comment]
No problem! I suppose I got caught up in old-fashioned design patterns thinking (I saw the callback as an Observer, whereas the function I was passing was more like a Strategy — it feels odd to mix the two). Still haven’t made the full transition into functional programming, I suppose! :-)

Thanks for helping me learn, and also figuring out a way to integrate our needs into your design!!
